version: '3'

services:
  mysql:
    image: mysql:5.5
    ports:
      - "13307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=openuser
      - MYSQL_PASSWORD=Password@1
      - MYSQL_DATABASE=opentutorials
    volumes:
      - "./env/mysql/conf.d:/etc/mysql/conf.d:ro"
      - "./env/mysql/data:/var/lib/mysql:rw"